### ISSUE TITLE
Convert input byte array to double or float.

### ISSUE THREAD

**Issue by turvyc** [turvyc/stuner#6]
In PitchDetector.java

**Comment by otaxar** [comment]
Byte array[] to float[] conversion implemented
4 bytes = 1 float value.

**Comment by otaxar** [comment]
Current values received appear to be out of range for float.
FLOAT	32bits	values range: 3 .4e–038 to 3.4e+038

**Comment by otaxar** [comment]
byte [] to float[] conversion updated. Originally, 4 bytes merged into 1 float. Currently, 2 bytes merged into short, then cast into float.

**Comment by otaxar** [comment]
Corrected by Colin
